"""empty message

Revision ID: 1d52575b0b82
Revises: 93a441ead648
Create Date: 2022-07-10 03:07:08.292629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d52575b0b82'
down_revision = '93a441ead648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=1028), nullable=False),
    sa.Column('venue', sa.String(length=128), nullable=False),
    sa.Column('flyer', sa.String(length=225), nullable=True),
    sa.Column('website', sa.String(length=225), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
