"""empty message

Revision ID: 93a441ead648
Revises: 
Create Date: 2022-07-10 02:57:03.860977

"""
from alembic import op
import sqlalchemy as sa
from datetime import date
from werkzeug.security import generate_password_hash


# revision identifiers, used by Alembic.
revision = '93a441ead648'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    temp_users_table = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###

    op.bulk_insert(temp_users_table,
        [
            {'id':0,
            'first_name' : 'Admin',
            'last_name' : 'First',
            'email': 'admin@admin.com',
            'password' : generate_password_hash(
            'password123', method='pbkdf2:sha256'),
            'profile_photo' : 'defualt_profile.png',
            'role': 'admin',
            'created_at' : date(2022, 10, 5)}
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
